# Generated by Django 5.0.7 on 2024-12-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
