# Generated by Django 5.0.7 on 2025-01-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_scheduled_date_evento_send_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='send_date',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
