# Generated by Django 5.0.7 on 2025-01-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_evento_send_date_alter_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
