# Generated by Django 5.0.7 on 2024-10-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0006_mensagem_data_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
