# Generated by Django 5.0.7 on 2024-10-23 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0007_artista_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='data_agendamento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
