# Generated by Django 5.0.7 on 2024-10-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0008_mensagem_data_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='data_agendamento',
            new_name='data_agendada',
        ),
    ]
