# Generated by Django 5.0.7 on 2024-12-02 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0009_rename_data_agendamento_mensagem_data_agendada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('scheduled_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Agendada')),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('sent', models.BooleanField(default=False, verbose_name='Enviada')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.artista')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
