# Generated by Django 5.0.7 on 2025-01-16 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0010_message_delete_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
